name: kantin_cerdas
description: "KantinCerdas adalah aplikasi Android berbasis Flutter untuk melihat menu, memperoleh rekomendasi berbantuan AI, dan memesan makanan agar dapat diambil di satu kantin kampus."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^18.0.1
  flutter_riverpod: ^3.4.3
  dio: ^5.11.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/plus-jakarta-400.ttf
          weight: 400
        - asset: assets/fonts/plus-jakarta-500.ttf
          weight: 500
        - asset: assets/fonts/plus-jakarta-600.ttf
          weight: 600

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logos/splash_logo.png

  android: true
  ios: false
  web: false

  android_gravity: center
  fullscreen: true

  android_12:
    color: "#FFFFFF"
    image: assets/images/logos/splash_logo.png
    icon_background_color: "#FFFFFF"
